
tasks:
  - name: docker_up
    command: |
      sudo docker-up >/dev/null 2>&1
      while ! docker ps; do
        sleep 1
      done
      docker run randyfay/cap-add-demo getcap /bin/nc.traditional
